# Generated by Django 5.0.6 on 2024-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=50)),
                ('carColor', models.CharField(max_length=50)),
                ('carPosition', models.CharField(max_length=50)),
            ],
        ),
    ]
